[images]
  remote_images = [
    "https://images.unsplash.com/*/*",
    "https://same-assets.com/*"
  ]

[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
